"""
modules/waf_detect.py
WAF / bot-protection fingerprinting and bypass-hint generation.

This module is purely analytical: it reads already-fetched response data
(headers, body, status) and returns structured information about what
protections are in place and which stealth techniques to apply next.
No requests are made here.
"""

from __future__ import annotations

import re
import logging
from dataclasses import dataclass, field
from typing import Dict, List, Optional

logger = logging.getLogger("CREEPER.waf_detect")


# ── WAF signatures (header-level) ─────────────────────────────────────────────

_HEADER_WAF_MAP: Dict[str, List[str]] = {
    "Cloudflare":   ["cf-ray", "cf-cache-status", "__cfduid", "cf-request-id"],
    "AWS WAF":      ["x-amzn-requestid", "x-amz-cf-id", "x-amz-apigw-id"],
    "Akamai":       ["x-akamai-request-id", "x-check-cacheable", "x-akamai-transformed"],
    "Imperva":      ["x-iinfo", "incap_ses", "visid_incap", "x-cdn"],
    "Sucuri":       ["x-sucuri-id", "x-sucuri-cache", "sucuri-clientid"],
    "F5 BIG-IP":    ["x-waf-status", "bigipserver", "f5-trafficshield"],
    "Barracuda":    ["barra_counter_session", "barracuda_dc_id"],
    "ModSecurity":  ["x-modsecurity-id"],
    "Fastly":       ["x-fastly-request-id", "fastly-restarts"],
    "Vercel":       ["x-vercel-id", "x-vercel-cache"],
    "Netlify":      ["x-nf-request-id"],
    "DDoS-Guard":   ["ddos-guard"],
    "Wordfence":    ["wf-blocked-reason"],
    "Radware":      ["x-rdwr-pop", "x-sl-compstate"],
}

# ── WAF signatures (body phrases) ─────────────────────────────────────────────

_BODY_WAF_PHRASES: Dict[str, List[str]] = {
    "Cloudflare":   ["attention required! | cloudflare", "ray id:", "cloudflare ray id"],
    "Imperva":      ["incapsula incident id", "powered by incapsula"],
    "Sucuri":       ["sucuri website firewall", "access denied | sucuri"],
    "DDoS-Guard":   ["ddos-guard.net", "checking your browser"],
    "AWS WAF":      ["aws waf could not forward", "request blocked"],
    "F5 BIG-IP":    ["the requested url was rejected", "your support id is"],
    "Barracuda":    ["barracuda networks", "your request has been blocked"],
    "Wordfence":    ["your access to this site has been limited", "generated by wordfence"],
    "ModSecurity":  ["not acceptable!", "406 not acceptable"],
    "Generic":      ["access denied", "403 forbidden", "blocked by security policy",
                     "bot protection", "please enable javascript and cookies",
                     "captcha", "human verification"],
}

# ── Challenge / CAPTCHA patterns ──────────────────────────────────────────────

_CAPTCHA_INDICATORS = [
    r'<div[^>]+id=["\']cf-wrapper["\']',      # Cloudflare
    r'data-sitekey=["\'][^"\']+["\']',         # reCAPTCHA / hCaptcha
    r'src=["\'][^"\']*recaptcha[^"\']*["\']',
    r'src=["\'][^"\']*hcaptcha[^"\']*["\']',
    r'<noscript>.*?captcha.*?</noscript>',
    r'window\._cf_chl_opt',                   # Cloudflare challenge
    r'__cf_challenge_running',
    r'jschl_vc',                              # CF JS challenge
]
_RE_CAPTCHA = [re.compile(p, re.IGNORECASE | re.DOTALL) for p in _CAPTCHA_INDICATORS]


@dataclass
class WAFResult:
    """Everything CREEPER learned about a site's bot-protection layer."""
    detected:        bool               = False
    vendor:          str                = ""
    confidence:      str                = ""   # "high" | "medium" | "low"
    evidence:        List[str]          = field(default_factory=list)
    captcha_present: bool               = False
    captcha_type:    str                = ""
    bypass_hints:    List[str]          = field(default_factory=list)
    soft_block:      bool               = False  # True → WAF returned 200 but blocked content
    hard_block:      bool               = False  # True → 4xx/5xx status from WAF


# ── Public analyser ───────────────────────────────────────────────────────────

def analyse(
    status:  int,
    headers: Dict[str, str],
    body:    str,
) -> WAFResult:
    """
    Analyse an HTTP response and return a WAFResult.

    Parameters
    ----------
    status  : HTTP status code
    headers : response headers dict (any case)
    body    : decoded response body (HTML)
    """
    result = WAFResult()
    lower_h = {k.lower(): v.lower() for k, v in headers.items()}
    lower_b  = body.lower()

    # ── 1. Header-based detection ──────────────────────────────────────────────
    for vendor, sigs in _HEADER_WAF_MAP.items():
        matched = [s for s in sigs if s in lower_h]
        if matched:
            _record(result, vendor, "high" if len(matched) > 1 else "medium",
                    [f"header:{s}" for s in matched])
            break

    # ── 2. Body-phrase detection ───────────────────────────────────────────────
    for vendor, phrases in _BODY_WAF_PHRASES.items():
        matched = [p for p in phrases if p in lower_b]
        if matched:
            conf = "high" if vendor != "Generic" else "low"
            _record(result, vendor or "Generic", conf,
                    [f"body:{p[:60]}" for p in matched])
            if not result.detected:
                result.detected = True

    # ── 3. Status-code hard-block ─────────────────────────────────────────────
    if status in {403, 406, 429, 503}:
        result.detected   = True
        result.hard_block = True
        if not result.vendor:
            result.vendor     = "Unknown"
            result.confidence = "low"
        result.evidence.append(f"status:{status}")

    # ── 4. Soft block (200 but challenge page) ────────────────────────────────
    if status == 200 and result.detected:
        result.soft_block = True

    # ── 5. CAPTCHA detection ──────────────────────────────────────────────────
    for i, pattern in enumerate(_RE_CAPTCHA):
        if pattern.search(body):
            result.captcha_present = True
            result.detected        = True
            if "hcaptcha" in _CAPTCHA_INDICATORS[i]:
                result.captcha_type = "hCaptcha"
            elif "recaptcha" in _CAPTCHA_INDICATORS[i] or "data-sitekey" in _CAPTCHA_INDICATORS[i]:
                result.captcha_type = "reCAPTCHA v2/v3"
            elif "cf" in _CAPTCHA_INDICATORS[i].lower():
                result.captcha_type = "Cloudflare Turnstile"
            else:
                result.captcha_type = "Unknown CAPTCHA"
            result.evidence.append(f"captcha:{result.captcha_type}")
            break

    # ── 6. Generate bypass hints ──────────────────────────────────────────────
    if result.detected:
        result.bypass_hints = _generate_hints(result, status, lower_h)

    return result


def _record(result: WAFResult, vendor: str, confidence: str, evidence: List[str]) -> None:
    if not result.detected:
        result.detected    = True
        result.vendor      = vendor
        result.confidence  = confidence
    result.evidence.extend(evidence)


def _generate_hints(result: WAFResult, status: int, lower_h: Dict) -> List[str]:
    hints: List[str] = []

    # Universal stealth hints
    hints.append("Increase delay_min/delay_max — slow down inter-request pacing")
    hints.append("Reduce concurrency to 1–2 workers for this target")

    if result.vendor == "Cloudflare":
        hints.append("Cloudflare: rotating UAs is usually insufficient — "
                     "consider a residential proxy or waiting for CF challenge TTL (~30 min)")
        if result.captcha_present:
            hints.append("Cloudflare Turnstile/CAPTCHA detected — automated bypass is not possible; "
                         "use authenticated session cookies (--custom-header Cookie=...)")
        hints.append("Cloudflare: set --no-ssl-verify=False; Cloudflare strips unusual TLS fingerprints")
        hints.append("Cloudflare: avoid Sec-Fetch-Site: cross-site; use none or same-origin")

    elif result.vendor == "Akamai":
        hints.append("Akamai: highly sensitive to TLS fingerprint (JA3). "
                     "Use Playwright with real Chromium binary instead of aiohttp")
        hints.append("Akamai: avoid sequential URL patterns — randomise crawl order")

    elif result.vendor == "Imperva":
        hints.append("Imperva: rotate IP via proxy; Imperva tracks IP reputation heavily")
        hints.append("Imperva: Accept-Language and Accept header must match UA exactly")

    elif result.vendor in ("Sucuri", "Wordfence", "ModSecurity"):
        hints.append(f"{result.vendor}: rule-based WAF — try URL-encoding special chars in params")
        hints.append(f"{result.vendor}: look for bypass paths (/xmlrpc.php, /wp-json/, /api/)")

    elif result.vendor == "AWS WAF":
        hints.append("AWS WAF: check for unprotected staging/API endpoints")
        hints.append("AWS WAF: X-Forwarded-For spoofing may bypass IP-based rules (test carefully)")

    elif result.vendor == "F5 BIG-IP":
        hints.append("F5: watch for cookie TS01* — it tracks session state")
        hints.append("F5: try HTTP/1.1 keep-alive with realistic Referer chain")

    if status == 429:
        hints.append("429 Too Many Requests: honour Retry-After header; "
                     "CREEPER backs off automatically but manual wait may help")

    if result.captcha_present and not result.vendor == "Cloudflare":
        hints.append("CAPTCHA present: solve manually once, copy session cookies, "
                     "pass them via custom_headers={'Cookie': '...'}")

    hints.append("Authenticated bug hunting: pass your session via "
                 "custom_headers={'Cookie': 'session=...', 'Authorization': 'Bearer ...'}")

    return hints


# ── Utility: quick single-line summary ────────────────────────────────────────

def summary_line(result: WAFResult) -> str:
    if not result.detected:
        return "No WAF/bot-protection detected"
    parts = [result.vendor or "Unknown WAF"]
    if result.confidence:
        parts.append(f"({result.confidence} confidence)")
    if result.captcha_present:
        parts.append(f"+ {result.captcha_type}")
    if result.hard_block:
        parts.append("[HARD BLOCK]")
    elif result.soft_block:
        parts.append("[SOFT BLOCK]")
    return " ".join(parts)
